import { createServerFn } from "@tanstack/react-start";

import { requireSupabaseAuth } from "@/integrations/supabase/auth-middleware";
import { supabaseAdmin } from "@/integrations/supabase/client.server";
import { z } from "zod";

/** Return current GitHub connection status for the user (no token exposed). */
export const getGithubConnection = createServerFn({ method: "GET" })
  .middleware([requireSupabaseAuth])
  .handler(async ({ context }) => {
    const { userId } = context;
    const { data, error } = await supabaseAdmin
      .from("github_connections")
      .select("github_username, scopes, created_at")
      .eq("user_id", userId)
      .maybeSingle();
    if (error) return { connected: false as const, error: error.message };
    if (!data) return { connected: false as const };
    return {
      connected: true as const,
      username: data.github_username,
      scopes: data.scopes,
      connectedAt: data.created_at,
    };
  });

/** Start OAuth: returns a GitHub authorize URL the client should redirect to. */
export const startGithubOAuth = createServerFn({ method: "POST" })
  .middleware([requireSupabaseAuth])
  .inputValidator(
    z.object({
      redirectTo: z.string().max(500).optional(),
    }).parse,
  )
  .handler(async ({ context, data }) => {
    const clientId = process.env.GITHUB_OAUTH_CLIENT_ID;
    if (!clientId) {
      return { ok: false as const, error: "GitHub OAuth not configured." };
    }
    const { userId } = context;
    const state = crypto.randomUUID() + "-" + crypto.randomUUID();

    const { error } = await supabaseAdmin.from("oauth_states").insert({
      state,
      user_id: userId,
      provider: "github",
      redirect_to: data.redirectTo ?? null,
    });
    if (error) return { ok: false as const, error: error.message };

    const url = new URL("https://github.com/login/oauth/authorize");
    url.searchParams.set("client_id", clientId);
    // `repo` covers reading and committing to private repos.
    // `workflow` is REQUIRED for writing files under `.github/workflows/`
    //   (e.g. the Maestro Cloud workflow file). GitHub split this out of
    //   `repo` in 2019 — without it, PUT on `contents/.github/workflows/...`
    //   returns 422.
    // `user:email` keeps `getGithubConnection.username` consistent.
    // Users who linked before this change will need to re-authorize once
    // (the studio detects missing scope and re-prompts).
    url.searchParams.set("scope", "repo workflow user:email");
    url.searchParams.set("state", state);
    url.searchParams.set("allow_signup", "true");

    return { ok: true as const, url: url.toString() };
  });

/** Disconnect (revoke locally only — user can revoke on GitHub side too). */
export const disconnectGithub = createServerFn({ method: "POST" })
  .middleware([requireSupabaseAuth])
  .handler(async ({ context }) => {
    const { userId } = context;
    const { error } = await supabaseAdmin
      .from("github_connections")
      .delete()
      .eq("user_id", userId);
    if (error) return { ok: false as const, error: error.message };
    return { ok: true as const };
  });

/** Push generated code to a brand-new GitHub repo owned by the user. */
export const pushCodeToGithub = createServerFn({ method: "POST" })
  .middleware([requireSupabaseAuth])
  .inputValidator(
    z.object({
      repoName: z
        .string()
        .min(1)
        .max(100)
        .regex(/^[a-zA-Z0-9._-]+$/, "Only letters, numbers, dots, dashes, underscores"),
      description: z.string().max(350).optional(),
      private: z.boolean().default(true),
      filename: z.string().min(1).max(200).regex(/^[a-zA-Z0-9._/-]+$/),
      content: z.string().min(1).max(500_000),
      commitMessage: z.string().max(200).optional(),
    }).parse,
  )
  .handler(async ({ context, data }) => {
    const { userId } = context;
    const { data: conn, error: connErr } = await supabaseAdmin
      .from("github_connections")
      .select("access_token, github_username")
      .eq("user_id", userId)
      .maybeSingle();
    if (connErr) return { ok: false as const, error: connErr.message };
    if (!conn) return { ok: false as const, error: "Not connected to GitHub." };

    const headers = {
      Accept: "application/vnd.github+json",
      Authorization: `Bearer ${conn.access_token}`,
      "X-GitHub-Api-Version": "2022-11-28",
      "Content-Type": "application/json",
      "User-Agent": "easy-mobile-ai",
    };

    // 1. Create repo
    const createRes = await fetch("https://api.github.com/user/repos", {
      method: "POST",
      headers,
      body: JSON.stringify({
        name: data.repoName,
        description: data.description ?? "Generated by Easy Mobile AI",
        private: data.private,
        auto_init: true,
      }),
    });
    if (!createRes.ok) {
      const txt = await createRes.text();
      return {
        ok: false as const,
        error: `GitHub create repo failed (${createRes.status}): ${txt.slice(0, 300)}`,
      };
    }
    const repo = (await createRes.json()) as {
      full_name: string;
      html_url: string;
      default_branch: string;
    };

    // 2. Add file via Contents API (auto_init created an initial commit, so file has no sha)
    const path = data.filename.replace(/^\/+/, "");
    const putRes = await fetch(
      `https://api.github.com/repos/${repo.full_name}/contents/${encodeURIComponent(path)}`,
      {
        method: "PUT",
        headers,
        body: JSON.stringify({
          message: data.commitMessage ?? `Add ${path}`,
          content: btoa(unescape(encodeURIComponent(data.content))),
          branch: repo.default_branch,
        }),
      },
    );
    if (!putRes.ok) {
      const txt = await putRes.text();
      return {
        ok: false as const,
        error: `GitHub commit failed (${putRes.status}): ${txt.slice(0, 300)}`,
        repoUrl: repo.html_url,
      };
    }

    return {
      ok: true as const,
      repoUrl: repo.html_url,
      fullName: repo.full_name,
    };
  });
