import { createFileRoute, Link } from "@tanstack/react-router";
import { useState } from "react";
import { ChevronDown } from "lucide-react";
import appPreview from "@/assets/app-preview.jpg";
import featureBackend from "@/assets/feature-backend.jpg";
import featureNative from "@/assets/feature-native.jpg";
import { SiteNav } from "@/components/SiteNav";

export const Route = createFileRoute("/")({
  component: Index,
  head: () => ({
    meta: [
      { title: "Mobivable — Chat your mobile app into the App Stores" },
      {
        name: "description",
        content:
          "Mobivable democratizes mobile app creation with AI. Go from idea to App Store and Google Play in minutes — just by chatting.",
      },
      { property: "og:title", content: "Mobivable — AI no-code mobile app builder" },
      {
        property: "og:description",
        content:
          "Describe your app. Mobivable's AI ships it to the App Store and Google Play in minutes.",
      },
    ],
  }),
});

function FaqItem({ question, answer, isLast }: { question: string; answer: string; isLast?: boolean }) {
  const [open, setOpen] = useState(false);
  return (
    <div className={`p-8 ${isLast ? "" : "border-b border-border"}`}>
      <button
        type="button"
        onClick={() => setOpen((o) => !o)}
        className="w-full flex items-center justify-between text-left focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary focus-visible:ring-offset-2 focus-visible:ring-offset-background"
        aria-expanded={open}
      >
        <span className="font-display text-xl uppercase tracking-tighter">{question}</span>
        <ChevronDown className={`size-5 text-muted transition-transform ${open ? "rotate-180" : ""}`} />
      </button>
      {open && (
        <p className="mt-4 text-sm text-muted leading-relaxed max-w-[70ch]">{answer}</p>
      )}
    </div>
  );
}

function Index() {
  return (
    <div className="min-h-screen bg-background text-foreground font-body selection:bg-primary selection:text-background">
      <SiteNav />

      {/* Hero */}
      <header id="engine" className="relative pt-20 pb-32 border-b border-border overflow-hidden">
        <div className="absolute inset-0 opacity-10 pointer-events-none">
          <div className="absolute top-0 left-1/2 -translate-x-1/2 w-px h-full bg-primary" />
          <div className="absolute top-1/2 left-0 -translate-y-1/2 w-full h-px bg-primary" />
        </div>

        <div className="max-w-7xl mx-auto px-6 grid grid-cols-1 lg:grid-cols-12 gap-12 items-center">
          <div className="lg:col-span-7 z-10 animate-reveal">
            <div className="inline-block px-2 py-1 border border-primary text-primary text-[10px] font-mono uppercase tracking-[0.2em] mb-6">
              AI Development Protocol v4.0
            </div>
            <h1 className="font-display text-7xl md:text-9xl uppercase leading-[0.85] tracking-tighter text-balance mb-8">
              Chat. <span className="text-primary">Ship.</span>
              <br />
              Dominate.
            </h1>
            <p className="text-xl text-muted max-w-[45ch] text-pretty leading-relaxed mb-10">
              Democratize mobile app creation with AI. Transform raw ideas into native iOS and
              Android binaries through a single conversational thread.
            </p>
            <div className="flex flex-wrap gap-4">
              <div className="flex flex-col gap-1">
                <button className="px-8 py-4 bg-primary text-background font-display text-lg uppercase tracking-wider hover:invert transition-all">
                  Start Generating
                </button>
                <span className="text-[10px] font-mono text-muted uppercase text-center mt-2">
                  Free during beta
                </span>
              </div>
            </div>
          </div>

          <div className="lg:col-span-5 relative animate-reveal [animation-delay:200ms]">
            <div className="relative bg-card/40 border border-border p-4 rounded-xl backdrop-blur-sm">
              <div className="space-y-4 font-mono text-xs">
                <div className="p-3 bg-foreground/5 border border-foreground/10 rounded-lg text-primary">
                  <span className="opacity-50">USR:</span> Build a luxury real estate app with high-res
                  galleries and dark mode.
                </div>
                <div className="p-3 bg-primary/10 border border-primary/20 rounded-lg">
                  <span className="text-primary">SYS:</span> Compiling UI components... Injecting
                  gallery modules... App Store metadata generated.
                </div>
              </div>
              <div className="mt-6 relative group">
                <img
                  src={appPreview}
                  alt="Live preview of a luxury real estate app generated by Mobivable"
                  width={1080}
                  height={1920}
                  className="w-full aspect-[9/16] object-cover rounded-lg outline outline-1 -outline-offset-1 outline-foreground/10 group-hover:outline-primary/50 transition-all"
                />
                <span className="absolute bottom-3 left-3 text-[10px] font-mono uppercase tracking-[0.2em] text-foreground/70 bg-background/60 px-2 py-1 rounded">
                  Live Preview: RealState_App_v1
                </span>
              </div>
            </div>
          </div>
        </div>
      </header>

      {/* Process */}
      <section id="process" className="py-24 border-b border-border">
        <div className="max-w-7xl mx-auto px-6">
          <div className="grid grid-cols-1 md:grid-cols-3 border border-border">
            {[
              { n: "01", t: "Describe", d: "Converse with our LLM-backed architect. Define features, styling, and logic in plain English." },
              { n: "02", t: "Refine", d: "Mobivable generates high-fidelity screens instantly. Tweak layouts and branding in the real-time preview." },
              { n: "03", t: "Launch", d: "One-click submission to App Store and Google Play. We handle the binaries, screenshots, and certification." },
            ].map((s, i) => (
              <div
                key={s.n}
                className={`p-8 ${i < 2 ? "md:border-r border-border" : ""} animate-reveal`}
                style={{ animationDelay: `${300 + i * 100}ms` }}
              >
                <span className="font-display text-4xl text-primary mb-4 block">{s.n}</span>
                <h3 className="font-display text-2xl uppercase mb-3">{s.t}</h3>
                <p className="text-sm text-muted leading-relaxed">{s.d}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Infrastructure */}
      <section id="infrastructure" className="py-24">
        <div className="max-w-7xl mx-auto px-6">
          <div className="mb-16 flex justify-between items-end border-b border-border pb-8">
            <h2 className="font-display text-5xl uppercase tracking-tighter">Core Infrastructure</h2>
            <div className="font-mono text-[10px] text-muted uppercase tracking-widest">
              Status: <span className="text-primary">Operational</span>
            </div>
          </div>

          <div className="grid grid-cols-1 lg:grid-cols-2 gap-12">
            <div className="group">
              <img
                src={featureBackend}
                alt="Automated backend generation visualized as code nodes"
                width={1200}
                height={800}
                loading="lazy"
                className="w-full aspect-video object-cover border border-border rounded-sm mb-6 group-hover:border-primary/40 transition-colors"
              />
              <h4 className="font-display text-xl uppercase mb-2">Self-Healing Logic</h4>
              <p className="text-sm text-muted max-w-[50ch]">
                AI doesn't just build the UI; it scaffolds your database, authentication, and API
                endpoints automatically.
              </p>
            </div>
            <div className="group">
              <img
                src={featureNative}
                alt="App Store published badge close up"
                width={1200}
                height={800}
                loading="lazy"
                className="w-full aspect-video object-cover border border-border rounded-sm mb-6 group-hover:border-primary/40 transition-colors"
              />
              <h4 className="font-display text-xl uppercase mb-2">Native Performance</h4>
              <p className="text-sm text-muted max-w-[50ch]">
                No wrappers. No lag. Mobivable compiles to Swift and Kotlin for true native 120fps
                fluid performance.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* Pricing */}
      <section id="pricing" className="py-24 border-b border-border">
        <div className="max-w-7xl mx-auto px-6">
          <div className="mb-16 flex justify-between items-end border-b border-border pb-8">
            <h2 className="font-display text-5xl uppercase tracking-tighter">Access Tiers</h2>
            <div className="font-mono text-[10px] text-muted uppercase tracking-widest">
              Pricing Matrix v1.0
            </div>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 border border-border">
            {([
              {
                plan: "free_beta" as const,
                name: "Free Beta",
                tag: "TIER_00",
                price: "$0",
                cadence: "/ forever",
                blurb: "For first-time builders shipping their initial app during the public beta.",
                cta: "Start Building",
                featured: false,
                features: [
                  "1 published app",
                  "Unlimited AI iterations",
                  "Native iOS + Android builds",
                  "App Store submission",
                  "Community support",
                ],
              },
              {
                plan: "starter" as const,
                name: "Starter",
                tag: "TIER_01",
                price: "$29",
                cadence: "/ month",
                blurb: "For solo founders running a small portfolio of live apps.",
                cta: "Go Starter",
                featured: true,
                features: [
                  "5 published apps",
                  "Unlimited AI iterations",
                  "Source code export",
                  "Custom domains",
                  "Priority queue compile",
                  "Email support",
                ],
              },
              {
                plan: "pro" as const,
                name: "Pro",
                tag: "TIER_02",
                price: "$99",
                cadence: "/ month",
                blurb: "For teams and operators shipping production apps at scale.",
                cta: "Go Pro",
                featured: false,
                features: [
                  "Unlimited published apps",
                  "Unlimited AI iterations",
                  "Source code export",
                  "Custom domains",
                  "Team workspaces",
                  "Advanced analytics",
                  "Dedicated support",
                ],
              },
            ]).map((p, i) => (
              <div
                key={p.tag}
                className={`p-8 flex flex-col ${i < 2 ? "md:border-r border-border" : ""} ${p.featured ? "bg-primary/5 relative" : ""}`}
              >
                {p.featured && (
                  <span className="absolute top-0 right-0 bg-primary text-background font-mono text-[10px] uppercase tracking-widest px-3 py-1">
                    Most Picked
                  </span>
                )}
                <span className="font-mono text-[10px] uppercase tracking-widest text-primary mb-4">{p.tag}</span>
                <h3 className="font-display text-3xl uppercase tracking-tighter mb-2">{p.name}</h3>
                <p className="text-sm text-muted mb-6 max-w-[35ch]">{p.blurb}</p>
                <div className="flex items-baseline gap-2 mb-8">
                  <span className="font-display text-5xl">{p.price}</span>
                  <span className="font-mono text-xs text-muted uppercase">{p.cadence}</span>
                </div>
                <ul className="space-y-3 mb-10 flex-1">
                  {p.features.map((f) => (
                    <li key={f} className="flex items-start gap-3 text-sm">
                      <span className="text-primary font-mono mt-0.5">+</span>
                      <span>{f}</span>
                    </li>
                  ))}
                </ul>
                <Link
                  to="/signup"
                  search={{ plan: p.plan }}
                  className={`block text-center w-full py-4 font-display text-base uppercase tracking-wider transition-all ${
                    p.featured
                      ? "bg-primary text-background hover:invert"
                      : "border border-border hover:border-primary hover:text-primary"
                  }`}
                >
                  {p.cta}
                </Link>
              </div>
            ))}
          </div>

          {/* Feature comparison */}
          <div className="mt-16 border border-border overflow-x-auto">
            <table className="w-full text-sm">
              <thead>
                <tr className="border-b border-border">
                  <th className="text-left p-5 font-mono text-[10px] uppercase tracking-widest text-muted">Capability</th>
                  <th className="text-center p-5 font-display uppercase tracking-tight">Free Beta</th>
                  <th className="text-center p-5 font-display uppercase tracking-tight text-primary">Starter</th>
                  <th className="text-center p-5 font-display uppercase tracking-tight">Pro</th>
                </tr>
              </thead>
              <tbody className="font-mono text-xs">
                {[
                  ["Published apps", "1", "5", "Unlimited"],
                  ["AI iterations", "Unlimited", "Unlimited", "Unlimited"],
                  ["Native iOS + Android compile", "•", "•", "•"],
                  ["App Store submission", "•", "•", "•"],
                  ["Source code export", "—", "•", "•"],
                  ["Custom domains", "—", "•", "•"],
                  ["Priority compile queue", "—", "•", "•"],
                  ["Team workspaces", "—", "—", "•"],
                  ["Advanced analytics", "—", "—", "•"],
                  ["Support", "Community", "Email", "Dedicated"],
                ].map((row, idx) => (
                  <tr key={row[0]} className={idx % 2 === 0 ? "bg-foreground/[0.02]" : ""}>
                    <td className="p-4 text-foreground uppercase tracking-wider">{row[0]}</td>
                    <td className="p-4 text-center text-muted">{row[1]}</td>
                    <td className="p-4 text-center text-foreground">{row[2]}</td>
                    <td className="p-4 text-center text-foreground">{row[3]}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      </section>

      {/* Testimonials */}
      <section className="py-24 border-b border-border">
        <div className="max-w-7xl mx-auto px-6">
          <div className="mb-16 flex justify-between items-end border-b border-border pb-8">
            <h2 className="font-display text-5xl uppercase tracking-tighter">Operator Log</h2>
            <div className="font-mono text-[10px] text-muted uppercase tracking-widest">
              Verified Builders
            </div>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            {[
              {
                code: "USR-0891",
                quote: "I described a crypto wallet app in three sentences. Twenty minutes later I had a TestFlight build. This is absurd.",
                author: "Maya Chen",
                role: "Indie Hacker",
              },
              {
                code: "USR-1044",
                quote: "We replaced a six-month agency timeline with a single afternoon. The output was production-grade Swift.",
                author: "James Okoro",
                role: "CTO, Baseline",
              },
              {
                code: "USR-1202",
                quote: "I don't know how to code. I shipped my meditation app to the App Store last week. That's the whole review.",
                author: "Sofia Reyes",
                role: "Solo Founder",
              },
            ].map((t) => (
              <div key={t.code} className="border border-border p-8 flex flex-col">
                <span className="font-mono text-[10px] uppercase tracking-widest text-primary mb-6">{t.code}</span>
                <p className="text-sm leading-relaxed text-foreground mb-8 flex-1">"{t.quote}"</p>
                <div>
                  <div className="font-display text-lg uppercase">{t.author}</div>
                  <div className="font-mono text-[10px] uppercase tracking-widest text-muted">{t.role}</div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* FAQ */}
      <section className="py-24 border-b border-border">
        <div className="max-w-7xl mx-auto px-6">
          <div className="mb-16 flex justify-between items-end border-b border-border pb-8">
            <h2 className="font-display text-5xl uppercase tracking-tighter">Signal Clarity</h2>
            <div className="font-mono text-[10px] text-muted uppercase tracking-widest">
              Common Queries
            </div>
          </div>
          <div className="border border-border">
            <FaqItem
              question="Do I need to know how to code?"
              answer="No. Mobivable is designed for builders who think in products, not syntax. You describe what you want in plain language, and the AI architect generates native iOS and Android binaries. Developers can still drop into the generated source if they want to extend."
            />
            <FaqItem
              question="What does 'native' actually mean here?"
              answer="It means Swift for iOS and Kotlin for Android — not webviews, not wrappers, not cross-platform abstractions. The AI compiles to platform-native code so your app runs at 120fps with full access to camera, push, biometrics, and every other OS capability."
            />
            <FaqItem
              question="How do App Store submissions work?"
              answer="You click one button. Mobivable handles certificates, screenshots, metadata, and the actual upload to App Store Connect and Google Play Console. You track the review status in the same dashboard where you built the app."
            />
            <FaqItem
              question="Can I export the source code?"
              answer="Yes. Every build includes the full generated project — Xcode workspace, Android Studio project, and backend scaffold. You own everything."
            />
            <FaqItem
              question="Is there a free tier?"
              answer="Initiate is free during public beta. It includes unlimited AI iterations, one published app, and community support. When we leave beta, existing free users keep their apps running."
              isLast
            />
          </div>
        </div>
      </section>

      {/* Footer CTA */}
      <footer className="bg-primary text-background py-24 px-6 overflow-hidden relative">
        <div className="absolute top-0 right-0 font-display text-[20vw] leading-none opacity-10 pointer-events-none translate-x-1/4 -translate-y-1/4">
          SHIP
        </div>
        <div className="max-w-7xl mx-auto relative z-10">
          <h2 className="font-display text-6xl md:text-8xl uppercase tracking-tighter leading-none mb-12">
            From idea to <br />
            App Store{" "}
            <span className="underline decoration-4 underline-offset-8">today</span>.
          </h2>
          <div className="flex flex-col md:flex-row gap-8 items-start md:items-center">
            <button className="px-12 py-6 bg-background text-primary font-display text-2xl uppercase hover:scale-105 transition-transform">
              Initialize Build
            </button>
            <div className="font-mono text-xs uppercase tracking-widest text-background/80">
              [0] No Credit Card Required <br />
              [1] Unlimited AI Iterations <br />
              [2] Global CDN Deployment
            </div>
          </div>
        </div>
      </footer>
    </div>
  );
}
