import { useState, useMemo, useCallback } from "react";
import { Code2, Copy, Check, Download, ChevronDown, FileCode2, Smartphone } from "lucide-react";

// Lazy-load Monaco to avoid SSR issues
let MonacoEditor: any = null;

interface CodeEditorPanelProps {
  projectResult: string | null;
  projectPrompt: string;
  projectModel: string;
  onClose: () => void;
}

/** Extracts JSON from a project result (may be wrapped in markdown code fences). */
function extractJSON(raw: string): string {
  const fenced = raw.match(/```(?:json)?\s*([\s\S]*?)```/);
  if (fenced) return fenced[1].trim();
  const braceStart = raw.indexOf("{");
  if (braceStart >= 0) return raw.slice(braceStart).trim();
  return raw;
}

/** Generates a synthetic React Native / Expo file tree from the app schema. */
function generateExpoFiles(jsonStr: string, prompt: string): Record<string, string> {
  const files: Record<string, string> = {};

  // app.json
  let appName = "MyApp";
  try {
    const parsed = JSON.parse(jsonStr);
    appName = parsed.name || parsed.appName || "MyApp";
  } catch { /* use default */ }

  files["app.json"] = JSON.stringify(
    {
      expo: {
        name: appName,
        slug: appName.toLowerCase().replace(/\s+/g, "-"),
        version: "1.0.0",
        orientation: "portrait",
        icon: "./assets/icon.png",
        splash: { image: "./assets/splash.png", resizeMode: "contain", backgroundColor: "#ffffff" },
        ios: { supportsTablet: true, bundleIdentifier: `com.mobivable.${appName.toLowerCase().replace(/\s+/g, "")}` },
        android: { adaptiveIcon: { foregroundImage: "./assets/adaptive-icon.png", backgroundColor: "#ffffff" }, package: `com.mobivable.${appName.toLowerCase().replace(/\s+/g, "")}` },
      },
    },
    null,
    2,
  );

  // package.json
  files["package.json"] = JSON.stringify(
    {
      name: appName.toLowerCase().replace(/\s+/g, "-"),
      version: "1.0.0",
      main: "expo/AppEntry.js",
      scripts: { start: "expo start", android: "expo start --android", ios: "expo start --ios", web: "expo start --web" },
      dependencies: {
        expo: "~52.0.0",
        "expo-status-bar": "~2.0.0",
        react: "18.3.1",
        "react-native": "0.76.3",
        "@react-navigation/native": "^7.0.0",
        "@react-navigation/bottom-tabs": "^7.0.0",
        "react-native-safe-area-context": "^4.12.0",
        "react-native-screens": "~4.0.0",
        "react-native-svg": "^15.8.0",
      },
      devDependencies: { "@types/react": "~18.3.0", typescript: "~5.6.0" },
    },
    null,
    2,
  );

  // App.tsx
  files["App.tsx"] = `import React from 'react';
import { NavigationContainer } from '@react-navigation/native';
import { createBottomTabNavigator } from '@react-navigation/bottom-tabs';
import { StatusBar } from 'expo-status-bar';
// Import your screens here
// import HomeScreen from './screens/HomeScreen';

const Tab = createBottomTabNavigator();

export default function App() {
  return (
    <NavigationContainer>
      <StatusBar style="auto" />
      <Tab.Navigator>
        {/* Add your screens here */}
        {/* <Tab.Screen name="Home" component={HomeScreen} /> */}
      </Tab.Navigator>
    </NavigationContainer>
  );
}
`;

  // tsconfig.json
  files["tsconfig.json"] = JSON.stringify(
    { extends: "expo/tsconfig.base", compilerOptions: { strict: true } },
    null,
    2,
  );

  // App schema (the AI-generated JSON)
  files["app-schema.json"] = jsonStr;

  // README
  files["README.md"] = `# ${appName}

> Generated by **Mobivable Agentic Mobile Studio**

## Prompt
${prompt}

## Getting Started
\`\`\`bash
npm install
npx expo start
\`\`\`

## Tech Stack
- React Native + Expo
- TypeScript
- React Navigation
`;

  return files;
}

export function CodeEditorPanel({ projectResult, projectPrompt, projectModel, onClose }: CodeEditorPanelProps) {
  const [activeFile, setActiveFile] = useState("app-schema.json");
  const [copied, setCopied] = useState(false);
  const [editorLoaded, setEditorLoaded] = useState(false);
  const [EditorComponent, setEditorComponent] = useState<any>(null);
  const [fileTreeOpen, setFileTreeOpen] = useState(true);

  // Generate files from project result
  const files = useMemo(() => {
    if (!projectResult) {
      return { "app-schema.json": "// No project generated yet.\n// Use the chat to generate your mobile app." };
    }
    const json = extractJSON(projectResult);
    try {
      // Pretty-print the JSON
      const parsed = JSON.parse(json);
      const prettyJson = JSON.stringify(parsed, null, 2);
      return generateExpoFiles(prettyJson, projectPrompt);
    } catch {
      return generateExpoFiles(json, projectPrompt);
    }
  }, [projectResult, projectPrompt]);

  const fileNames = Object.keys(files);
  const currentContent = files[activeFile] ?? "";

  // Lazy load Monaco on first render (client-side only)
  useState(() => {
    if (typeof window !== "undefined") {
      import("@monaco-editor/react").then((mod) => {
        setEditorComponent(() => mod.default);
        setEditorLoaded(true);
      });
    }
  });

  const handleCopy = useCallback(() => {
    navigator.clipboard.writeText(currentContent);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }, [currentContent]);

  const languageMap: Record<string, string> = {
    ".json": "json",
    ".tsx": "typescriptreact",
    ".ts": "typescript",
    ".md": "markdown",
  };
  const ext = activeFile.slice(activeFile.lastIndexOf("."));
  const lang = languageMap[ext] ?? "plaintext";

  return (
    <section className="flex flex-1 lg:flex-none lg:w-[540px] min-h-[60vh] lg:min-h-0 lg:shrink-0 border-b lg:border-b-0 lg:border-r border-border flex-col bg-card/40">
      {/* Header */}
      <header className="p-4 border-b border-border flex items-center justify-between gap-3">
        <div className="flex items-center gap-3 min-w-0">
          <div className="h-9 w-9 rounded-lg bg-primary/15 grid place-items-center shrink-0">
            <Code2 className="h-4.5 w-4.5 text-primary" />
          </div>
          <div className="min-w-0">
            <h2 className="font-display text-base truncate">Generated Code</h2>
            <p className="text-[10px] text-muted-foreground font-mono truncate">
              Expo / React Native · {projectModel}
            </p>
          </div>
        </div>
        <div className="flex items-center gap-2">
          <button
            type="button"
            onClick={handleCopy}
            className="inline-flex items-center gap-1.5 text-[10px] font-mono uppercase tracking-widest text-muted-foreground hover:text-foreground transition-colors px-2 py-1.5 rounded-lg border border-border hover:bg-muted/40"
          >
            {copied ? <Check className="h-3 w-3 text-emerald-500" /> : <Copy className="h-3 w-3" />}
            {copied ? "Copied" : "Copy"}
          </button>
          <button
            type="button"
            onClick={onClose}
            className="text-[10px] uppercase tracking-widest text-muted-foreground hover:text-foreground px-2 py-1.5"
          >
            Close
          </button>
        </div>
      </header>

      <div className="flex flex-1 overflow-hidden">
        {/* File tree */}
        <div className="w-44 shrink-0 border-r border-border bg-background/50 overflow-y-auto">
          <div className="p-2">
            <button
              type="button"
              onClick={() => setFileTreeOpen(!fileTreeOpen)}
              className="flex items-center gap-1.5 text-[10px] font-mono uppercase tracking-widest text-muted-foreground w-full px-2 py-1.5 hover:text-foreground"
            >
              <ChevronDown className={`h-3 w-3 transition-transform ${fileTreeOpen ? "" : "-rotate-90"}`} />
              <Smartphone className="h-3 w-3" />
              Project
            </button>
            {fileTreeOpen && (
              <div className="mt-1 space-y-0.5">
                {fileNames.map((name) => {
                  const isActive = name === activeFile;
                  const isJson = name.endsWith(".json");
                  const isTsx = name.endsWith(".tsx") || name.endsWith(".ts");
                  return (
                    <button
                      key={name}
                      type="button"
                      onClick={() => setActiveFile(name)}
                      className={`w-full text-left flex items-center gap-1.5 px-2 py-1.5 rounded text-[11px] transition-colors ${
                        isActive
                          ? "bg-primary/10 text-primary font-medium"
                          : "text-muted-foreground hover:bg-muted/40 hover:text-foreground"
                      }`}
                    >
                      <FileCode2 className={`h-3 w-3 shrink-0 ${
                        isJson ? "text-amber-500" : isTsx ? "text-blue-500" : "text-muted-foreground"
                      }`} />
                      <span className="truncate font-mono text-[10px]">{name}</span>
                    </button>
                  );
                })}
              </div>
            )}
          </div>
        </div>

        {/* Editor */}
        <div className="flex-1 overflow-hidden">
          {editorLoaded && EditorComponent ? (
            <EditorComponent
              height="100%"
              language={lang}
              value={currentContent}
              theme="vs-dark"
              options={{
                readOnly: true,
                minimap: { enabled: false },
                fontSize: 12,
                lineNumbers: "on",
                scrollBeyondLastLine: false,
                wordWrap: "on",
                padding: { top: 12 },
                renderLineHighlight: "none",
                folding: true,
                bracketPairColorization: { enabled: true },
              }}
            />
          ) : (
            <pre className="p-4 text-xs font-mono text-foreground/70 overflow-auto h-full whitespace-pre-wrap bg-[#1e1e1e] text-[#d4d4d4]">
              {currentContent}
            </pre>
          )}
        </div>
      </div>

      {/* Footer status bar */}
      <div className="border-t border-border px-4 py-1.5 flex items-center justify-between text-[9px] font-mono text-muted-foreground bg-background/50">
        <span>{lang.toUpperCase()} · {activeFile}</span>
        <span>{currentContent.split("\n").length} lines</span>
      </div>
    </section>
  );
}
